version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: todo_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data
    networks:
      - local_network
    restart: on-failure:3

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
    ports:
      - "${PG_WEB}:8081"
    networks:
      - local_network
    restart: on-failure:3

  redis:
    image: redis:alpine
    container_name: todo_redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - todo_redis_data:/data
    networks:
      - local_network
    restart: on-failure:3

networks:
  local_network:

volumes:
  todo_postgres_data:
  todo_redis_data:
